<!-- creation_collab.phtml -->
<h2>Créer un nouveau collaborateur</h2>
<form action="create" method="post">
    <div>
        <label for="nom">Nom du collaborateur:</label>
        <input type="text" id="nom" name="nom" required>
    </div>
    <div>
        <label for="niveau">Niveau:</label>
        <select id="niveau" name="niveau" required>
            <option value="1">Stagiaire</option>
            <option value="2">Junior</option>
            <option value="3">Senior</option>
        </select>
    </div>
    <div>
        <label for="prime">Prime Embauche:</label>
        <input type="number" id="prime" name="prime" required>
    </div>
    <div>
        <input type="submit" value="Créer Collaborateur">
    </div>
</form>

<!-- Ajoutez ici les liens vers les fichiers JavaScript de Bootstrap -->
<script src="https://cedn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>